name: ecoevolity-model-prior-project
dependencies:
  - python=3.7.6
  - scipy=1.4.1
  - numpy=1.18.1
  - pyyaml=5.3
  - pip=20.0.2
  - pip:
      - git+git://github.com/phyletica/pycoevolity.git@master
      - matplotlib==3.1.3
